#ifndef __MYUN2__RESPONDER__LEXER__HPP__
#define __MYUN2__RESPONDER__LEXER__HPP__

namespace myun2
{
	namespace responder
	{
		struct null_type {};

		template <
			typename T1 = null_type,
			typename T2 = null_type,
			typename T3 = null_type,
			typename T4 = null_type,
			typename T5 = null_type,
			typename T6 = null_type,
			typename T7 = null_type,
			typename T8 = null_type,
			typename T9 = null_type,
			typename T10 = null_type,
			typename T11 = null_type,
			typename T12 = null_type,
			typename T13 = null_type,
			typename T14 = null_type,
			typename T15 = null_type,
			typename T16 = null_type,
			typename T17 = null_type,
			typename T18 = null_type,
			typename T19 = null_type,
			typename T20 = null_type,
			typename T21 = null_type,
			typename T22 = null_type,
			typename T23 = null_type,
			typename T24 = null_type,
			typename T25 = null_type,
			typename T26 = null_type,
			typename T27 = null_type,
			typename T28 = null_type,
			typename T29 = null_type,
			typename T30 = null_type,
			typename T31 = null_type,
			typename T32 = null_type,
			typename T33 = null_type,
			typename T34 = null_type,
			typename T35 = null_type,
			typename T36 = null_type,
			typename T37 = null_type,
			typename T38 = null_type,
			typename T39 = null_type,
			typename T40 = null_type,
			typename T41 = null_type,
			typename T42 = null_type,
			typename T43 = null_type,
			typename T44 = null_type,
			typename T45 = null_type,
			typename T46 = null_type,
			typename T47 = null_type,
			typename T48 = null_type,
			typename T49 = null_type,
			typename T50 = null_type,
			typename T51 = null_type,
			typename T52 = null_type,
			typename T53 = null_type,
			typename T54 = null_type,
			typename T55 = null_type,
			typename T56 = null_type,
			typename T57 = null_type,
			typename T58 = null_type,
			typename T59 = null_type,
			typename T60 = null_type,
			typename T61 = null_type,
			typename T62 = null_type,
			typename T63 = null_type,
			typename T64 = null_type>
		struct lexer
		{
		public:
			lexer(
				const T1& t1 = null_type(),
				const T2& t2 = null_type(),
				const T3& t3 = null_type(),
				const T4& t4 = null_type(),
				const T5& t5 = null_type(),
				const T6& t6 = null_type(),
				const T7& t7 = null_type(),
				const T8& t8 = null_type(),
				const T9& t9 = null_type(),
				const T10& t10 = null_type(),
				const T11& t11 = null_type(),
				const T12& t12 = null_type(),
				const T13& t13 = null_type(),
				const T14& t14 = null_type(),
				const T15& t15 = null_type(),
				const T16& t16 = null_type(),
				const T17& t17 = null_type(),
				const T18& t18 = null_type(),
				const T19& t19 = null_type(),
				const T20& t20 = null_type(),
				const T21& t21 = null_type(),
				const T22& t22 = null_type(),
				const T23& t23 = null_type(),
				const T24& t24 = null_type(),
				const T25& t25 = null_type(),
				const T26& t26 = null_type(),
				const T27& t27 = null_type(),
				const T28& t28 = null_type(),
				const T29& t29 = null_type(),
				const T30& t30 = null_type(),
				const T31& t31 = null_type(),
				const T32& t32 = null_type(),
				const T33& t33 = null_type(),
				const T34& t34 = null_type(),
				const T35& t35 = null_type(),
				const T36& t36 = null_type(),
				const T37& t37 = null_type(),
				const T38& t38 = null_type(),
				const T39& t39 = null_type(),
				const T40& t40 = null_type(),
				const T41& t41 = null_type(),
				const T42& t42 = null_type(),
				const T43& t43 = null_type(),
				const T44& t44 = null_type(),
				const T45& t45 = null_type(),
				const T46& t46 = null_type(),
				const T47& t47 = null_type(),
				const T48& t48 = null_type(),
				const T49& t49 = null_type(),
				const T50& t50 = null_type(),
				const T51& t51 = null_type(),
				const T52& t52 = null_type(),
				const T53& t53 = null_type(),
				const T54& t54 = null_type(),
				const T55& t55 = null_type(),
				const T56& t56 = null_type(),
				const T57& t57 = null_type(),
				const T58& t58 = null_type(),
				const T59& t59 = null_type(),
				const T60& t60 = null_type(),
				const T61& t61 = null_type(),
				const T62& t62 = null_type(),
				const T63& t63 = null_type(),
				const T64& t64 = null_type())
		};
	}
}

#endif//__MYUN2__RESPONDER__PATTERN_MATCHER__HPP__
